name: Build APK

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get project
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: "8.13"

      - name: Install Android SDK
        run: |
          SDKMANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"

          if [ ! -x "$SDKMANAGER" ]; then
            SDKMANAGER="$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager"
          fi

          yes | "$SDKMANAGER" --licenses >/dev/null || true
          "$SDKMANAGER" "platforms;android-36" "build-tools;36.0.0"

      - name: Extract project
        run: |
          rm -rf extracted
          mkdir extracted
          unzip.LupaOCR_Android_Project_v0.2_fixed.zip" -d extracted

          test -f "extracted/LupaOCR/settings.gradle.kts"
          test -f "extracted/LupaOCR/app/build.gradle.kts"

          echo "Project extracted successfully"

      - name: Fix compatible dependencies
        run: |
          FILE="extracted/LupaOCR/app/build.gradle.kts"

          sed -i 's/androidx.core:core-ktx:1.19.0/androidx.core:core-ktx:1.17.0/' "$FILE"
          sed -i 's/androidx.activity:activity-ktx:1.13.0/androidx.activity:activity-ktx:1.11.0/' "$FILE"

          grep -E "compileSdk|targetSdk|core-ktx|activity-ktx" "$FILE"

      - name: Build Lupa APK
        working-directory: ./extracted/LupaOCR
        run: |
          gradle --no-daemon :app:assembleDebug

      - name: Save APK
        uses: actions/upload-artifact@v4
        with:
          name: Lupa-OCR-APK
          path: extracted/LupaOCR/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
